sudo: false
language: node_js
node_js:
  - "8.4.0"

cache: yarn

git:
    submodules: false

before_install:
  - git submodule update --init --recursive
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_$HUGO_VERSION_Linux-64bit.tar.gz
  - mkdir -p ~/.bin
  - tar -xfz hugo_$HUGO_VERSION_Linux-64bit.tar.gz -C ~/.bin
  - export PATH="$HOME/.bin:$HOME/.yarn/bin:$PATH"

install:
  - cd themes/erianna
  - yarn install --no-progress
  - cd ../..

script:
  - cd themes/erianna
  - yarn run build
  - cd ../..
  - hugo