sudo: false
language: node_js

node_js:
  - 12.4.0

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mkdir -p ~/.bin
  - tar -xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -C ~/.bin
  - export PATH="$HOME/.bin:$HOME/.yarn/bin:$PATH"

install:
  - cd themes/erianna
  - yarn install --no-progress
  - cd ../..

script:
  - cd themes/erianna
  - yarn run build
  - cat data/assets/main/assets.json
  - cat data/assets/main/sri.yml
  - cd ../..
  - export HUGO_ENV="production"
  - hugo
  - export JSON_FILE_LIST=$(find ./public -maxdepth 10 -type f -not -name 't_*' | sed  "s/.\/public//g" | jq -R -s -c 'split("\n")')

deploy:
  provider: s3
  access_key_id: SGQOQ723657BW75HYG7Q
  secret_access_key:
    secure: uBU2Jd8XgVRl3JwTzrK1SXjyVJn83OHvWdXJoMMTm5o/MMdW059Zq7agugqjF3LbxK/T0UuN5YcxNSAWHKU5dK6Hz8FpCgubuZ5ZzpC7V6r/ZiimkUik2uh2ksb0MgUQ34hc777X9CKZiAIZJzhPXBkXSY08EiWn7IQXPZq/lnJzIPtDa3zKadz9OAgTyt/ntpxt92JiawNsQjzZ+5OpH5v2QOd0rzbyuN/8ml/HYU2lZok0JBZ1zfpK47pEpGqx/dUPGHm4yEGCXueiSzydR0ogWxKwipurMb9/ODJspT25nlNqvAfJDbBZhSVcz0KcDazm5K6ToKEcQhTcSuRiLZzAM0bjgcFmg6pbUsQxu1NIGar9CPdcPhagcQB/G/5CAvfFHpwLP7GUawXoAq2vyd3JMkPm1GplryHuS/eSxXadve0Hc3S5YqEpSAOc+Rhf2ZFyGknZBGamJ1U8Dvq2qmqsiI+AfV+JWYN0GGTB3iv/wK+8oY9YsIKnVmWa/zSc/CE3hpVceIOl0/0sM3vDEPxx7Of52mYWtJPJ7eQ5yBY3DTYZyH1cj/EISsGS1Kx9z4hmV5F4Lhit3xHN80lnBqaQ6NVXnLdgbTcQYqovps+SCxu1srNfbtUN5xciVrMD9dl/+hq4JSzlAwqJyrvozyFFN2rEOBL+l/9kJwfloF0=
  bucket: www-erianna-com
  local-dir: public
  skip_cleanup: true
  endpoint: https://sfo2.digitaloceanspaces.com
  on:
    repo: charlesportwoodii/www.erianna.com
    branch: master