---
baseURL: "https://www.erianna.com"
enableGitInfo: true
enableRobotsTXT: true
languageCode: en-us
noChmod: true
noTimes: true
params:
  googleAnalytics: "UA-21577234-3"
  adsense: "ca-pub-4002758512930390"
  Author: "Charles R. Portwood II"
  Email: charlesportwoodii@erianna.com
  social:
      github: "https://www.github.com/charlesportwoodii"
      twitter: "https://www.twitter.com/charlesportwood"
      linkedin: "https://www.linkedin.com/in/charlesportwoodii"
      gpg: "https://keybase.io/charlesportwood/key.asc"
  intro: "Topics on software development, business, and writing."
  nav:
    - { url: "/about", text: "About Me" }
    - { url: "/books", text: "Books" }
    - { url: "/packages", text: "Repositories" }
permalinks:
  post: "/:year/:month/:title/"
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
theme: erianna
title: "Erianna | Charles R. Portwood II"
Paginate: 10
PaginatePath: "blog"
uglyurls: false
canonifyURLs: false
relativeURLs: false