version: '3.3'
services:
  webpack:
    image: node:10-alpine
    volumes:
      - ${PWD-.}:/var/www
      - nodejs:/var/www/themes/erianna/node_modules
    ports:
      - "8080:8080"
      - "8081:8081"
    command: |
      sh -c "apk add --no-cache bash curl; touch ~/.bashrc; curl -o- -L https://yarnpkg.com/install.sh | bash; bash -lc \"yarn install --no-progress; yarn run dev\""
    working_dir: /var/www/themes/erianna

volumes:
  nodejs: