services:
  webpack:
    image: node:22-alpine
    volumes:
      - ${PWD-.}:/var/www
      - nodejs:/var/www/themes/erianna/node_modules
      - /var/www/themes/erianna/.yarnrc.yml
    ports:
      - "8080:8080"
      - "8081:8081"
    command: |
      sh -c "yarn set version berry; yarn install; yarn run dev"
    working_dir: /var/www/themes/erianna
    environment:
      DEBUG: 1
      NODE_OPTIONS: --openssl-legacy-provider

  hugo:
    image: jojomi/hugo
    ports:
      - "1313:1313"
    volumes:
      - ${PWD-.}:/var/www
      - nodejs:/var/www/themes/erianna/node_modules
    working_dir: /var/www
    command: |
      hugo server -t erianna --bind 0.0.0.0 --enableGitInfo --noHTTPCache --log

volumes:
  nodejs: